### ISSUE TITLE
HiDef Profile

### ISSUE THREAD

**Issue by ohlawdie** [Silentspy/terrariaxnb2png#1]
Hey Silentspy, 

I'm getting this error when I try to process any .xnb from the game Axiom Verge. 

"This file was compiled for the HiDef profile, and cannot be loaded into a Reach GraphicsDevice."

Do you know of any way around this? 
Thanks

**Comment by SebastiaanLubbers** [comment]
Try setting https://github.com/Silentspy/terrariaxnb2png/blob/deaa306bb847cb44cf93851f8046e8b6401bb131/TerrariaXNB2PNG/GraphicsDeviceService.cs#L65 the GraphicsProfile to GraphicsProfile.HiDef.

**Comment by Silentspy** [comment]
I applied https://github.com/Silentspy/terrariaxnb2png/pull/2 to fix this issue as with other minor fixes. Thank you @tolik518!

**Comment by tolik518** [comment]
I'm glad I could help :)  

This is the first time I committed to an open source project by the way
